# Generated by Django 2.2 on 2020-10-24 14:36

import django.core.validators
from django.db import migrations, models
import heystack_search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('file', models.FileField(upload_to=heystack_search.models.file_upload, validators=[django.core.validators.FileExtensionValidator(['ppsx', 'ppt', 'pptm', 'pptx', 'pdf', 'PDF'])])),
            ],
        ),
    ]
